name: AdBlock
version: 1.2
author: Sinrel Group
main: org.sinrel.adblock.AdBlock
description: blocked servers commercial

permissions:
  adBlock.admin:
    description: Allow to avoid punishment
    default: op
    