name: adBlock
version: 1.1
author: Akirus
main: org.sinrel.adblock.AdBlock
description: blocked servers commercial

permissions:
  adBlock.admin:
    description: Allow to avoid punishment
    default: op
    